#ifndef __DMLFW__LINEAR__REGRESSION__
#define __DMLFW__LINEAR__REGRESSION__
#include<dmlfw_matrix.h>
#include<dmlfw_vector.h>
#include<inttypes.h>

dmlfw_row_vec_double * dmlfw_linear_regression_gradient_descent_fit_line(dmlfw_mat_double *input_features_matrix,dmlfw_column_vec_double *target_values_vector,double learning_rate,double regularization_parameter,uint64_t number_of_iterations,uint8_t (*on_each_iteration) (uint64_t iteration_number,double error_value,dmlfw_column_vec_double *predicted_values_vector));

dmlfw_column_vec_double * dmlfw_linear_regression_predict(dmlfw_mat_double *input_features_matrix,dmlfw_row_vec_double *trained_parameters);

dmlfw_row_vec_double * dmlfw_linear_regression_normal_equation_fit_line(dmlfw_mat_double *input_features_matrix,dmlfw_column_vec_double *target_values_vector);
#endif
