#ifndef __DMLFW__MODEL__ACCURACY__SCORE__
#define __DMLFW__MODEL__ACCURACY__SCORE__
#include<dmlfw_vector.h>
double dmlfw_get_r2_score(dmlfw_column_vec_double *target_values_vector,dmlfw_column_vec_double *predicted_values_vector);
#endif
