#ifndef __MLFW__MODEL__ACCURACY__SCORE__
#define __MLFW__MODEL__ACCURACY__SCORE__
#include<mlfw_vector.h>
double mlfw_get_r2_score(mlfw_column_vec_double *target_values_vector,mlfw_column_vec_double *predicted_values_vector);
#endif
