#ifndef __DMLFW__ERROR__
#define __DMLFW__ERROR__
/**
 * @file dmlfw_error.h
 * @brief Centralized error handling interface for the framework.
 * @ingroup ml-framework
 * @{
 *
 * @author Mohammed Daniyal
 * @version 1.0
 * @date 2025-09-26
 *
 *
 * This module provides functions to check and retrieve error statuses,
 * error codes, human-readable messages, and debugging information
 * generated by framework APIs.
 *
 * All framework functions that can fail internally set an error status.
 * Users should check for errors immediately after calls using `dmlfw_error()`.
 *
 * If an error occurs, retrieve:
 * - The error code via `dmlfw_get_error_code()`.
 * - The error message via `dmlfw_get_error_string()`.
 * - Debugging details via `dmlfw_get_debug_string()`.
 *
 * @example example_dmlfw_error.c
 * Example usage:
 * @code
 * #include <stdio.h>
 * #include <stdlib.h>
 * #include <dmlfw_matrix.h>
 * #include <dmlfw_error.h>
 *
 * int main(void) {
 *     char err[512];
 *     char debug[512];
 *
 *     dmlfw_mat_double *matrix = NULL;
 *     // Example framework call
 *     matrix = dmlfw_mat_double_create_new(2, 3);
 *
 *     if(dmlfw_error()) {
 *         dmlfw_get_error_string(err, sizeof(err));
 *         dmlfw_get_debug_string(debug, sizeof(debug));
 *         printf("Error: %s, Debugging: %s\n", err, debug);
 *         // Handle error and clean up
 *         return EXIT_FAILURE;
 *     }
 *
 *     // Do some work with matrix...
 *
 *     // Cleanup
 *     dmlfw_mat_double_destroy(matrix);
 *
 *     return EXIT_SUCCESS;
 * }
 * @endcode
 * Note: For `dmlfw_get_error_string()` and `dmlfw_get_debug_string()`,
 * pass a character buffer of sufficient size (typically >=512 bytes)
 * to safely hold the returned string.
 *
 * This enables robust and consistent error tracking across the framework.
 *
 */


#include <inttypes.h>
#include <dmlfw_types.h>

/**
 * @brief Checks if the last framework call resulted in an error.
 * @return Non-zero if an error occurred, zero otherwise.
 */
uint8_t dmlfw_error(void);

/**
 * @brief Retrieves the error code of the last error.
 * @return Error code as a 32-bit unsigned integer.
 */
uint32_t dmlfw_get_error_code(void);

/**
 * @brief Copies the last error message into the provided character buffer.
 * @param error_string Buffer to hold the error message (should be at least 512 bytes).
 * @param size Size of the buffer in bytes.
 */
void dmlfw_get_error_string(char *error_string, uint32_t size);

/**
 * @brief Copies detailed debug information about the last error into the provided character buffer.
 * @param debug_string Buffer to hold the debug information (should be at least 512 bytes).
 * @param size Size of the buffer in bytes.
 */
void dmlfw_get_debug_string(char *debug_string, uint32_t size);

/**
 * @brief Gets the length of the last error message string.
 * @return Length in bytes of the error message.
 */
uint32_t dmlfw_get_error_string_length(void);

/**
 * @brief Gets the length of the last debug string.
 * @return Length in bytes of the debug string.
 */
uint32_t dmlfw_get_debug_string_length(void);

#endif // __DMLFW__ERROR__

/** @} */ ///< End of error_handling group
